version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1

jobs:
  release:
    executor: cypress/base-12-14-0
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run semantic-release 🚀

workflows:
  build:
    jobs:
      - cypress/run:
          name: Cypress run 🛎📦🧪
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - Cypress run 🛎📦🧪
